controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

index:
    path: /
    controller: App\Controller\BaseController::index

error_404:
    path: /{catchall}
    controller: App\Controller\BaseController::error404
    requirements:
        catchall: .*

